defaults: &defaults
  upload_max_size: 20
  image:
    density: 144 
    size: 720
    thumbnail_size: 300 

development:
  <<: *defaults
  java: /usr/java/latest/bin/java
  convert: /usr/bin/convert
  jodconverter: /home/yukatou/src/jodconverter-core-3.0-beta-4/lib/jodconverter-core-3.0-beta-4.jar

production:
  <<: *defaults
  java: /usr/bin/java
  convert: /usr/bin/convert
  jodconverter: /opt/jodconverter-core-3.0-beta-4/lib/jodconverter-core-3.0-beta-4.jar
