defaults: &defaults

development:
  java: /usr/bin/java
  convert: /usr/bin/convert
  jodconverter: /opt/jodconverter-core-3.0-beta-4/lib/jodconverter-core-3.0-beta-4.jar
production:
  java: /usr/bin/java
  convert: /usr/bin/convert
  jodconverter: /opt/jodconverter-core-3.0-beta-4/lib/jodconverter-core-3.0-beta-4.jar
